# Site settings
name: maque
email: maqueyz@163.com
author: maqueyz
url: https://maqueredkop.github.io
resume_site: https://maqueredkop.github.io
github: https://github.com/maqueredkop/
baseurl: ""
description: 麻雀虽小 五脏俱全
meta_description: 个人博客
#motto: 目送归鸿 手挥五弦 俯仰自得 游心太玄
banner: ""

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: maqueredkop
highlighter: rouge

# Build settings
markdown: kramdown

## add visit number stat
<script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>
            <span id="busuanzi_container_site_pv">本站总访问量<span id="busuanzi_value_site_pv"></span>次</span>

FB:
  comments :
    provider : disqus
    disqus:
        short_name : maqueblog
    livefyre :
        short_name : 123
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
