# Site settings
name: maque
email: maqueyz@163.com
author: maqueyz
url: https://maqueredkop.github.io
resume_site: https://maqueredkop.github.io
github: https://github.com/maqueredkop/
baseurl: "/LessOrMore"
description: Actually, less is more!
meta_description: 个人博客
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: maqueredkop
highlighter: Pygments

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
